### PR TITLE
Add required files for packaging and uploading to PyPI.

### PR DESCRIPTION
**Pull request by mapitman**
This will allow developers to install the package by typing `pip install
unicorn-hat-sim`.

I made a few assumptions, such as adding the MIT license. If you want to release it under some other license, let me know and I'll change it.

The `packaging.md` file has info on how to build the package and upload to PyPI.

### CODE REVIEW

**Comment by mapitman** [comment]
Hi, just wondering if you are open to accepting this pull request. If you don't want to maintain the project anymore or deal with the packaging stuff, I can package it up from my fork and publish it.

**Comment by overengen** [comment]
Sorry that was not my intention, i think i might accidentally have pushed a
button too many.

Love your work thou!!!

Downloaded it to try it out while waiting to set up my raspberry with a
true physical unicorn.

Also made some modifications to create a bigger screen for a future
art-project.

It was super easy thanks to nice coding of yours!!!!


Thanks for reading this mail!

/regards Magnus

**Comment by wbprice** [comment]
I'd also like to be able to download this project from PyPi. What else needs to be done before the project can be published?

**Comment by mapitman** [comment]
I went ahead and published a package. If @jayniz wants to take ownership at some later date, I'll make him the owner.

**Comment by jayniz** [comment]
Didn’t see there are PRs here. Sorry, and thank you 😊 Should I just give you access to the repo so you can help maintain @mapitman?

**Comment by mapitman** [comment]
Sure, also if you create a PyPi account I will figure out how to add you as an owner for the package I published.

**Pull request merged**
